### ISSUE TITLE
Upgraded to Big Sur, now it doesn't work and cannot uninstall

### ISSUE THREAD

**Issue by ospfranco** [360Controller/360Controller#1118]
### Type of Controller
Replace this text with: Xbox 360

### OS Version
macOS Big Sur

### Driver Version
Version 1.0.0-alpha.6

### Connection Method
Wired

### Response of Controller
None

### Response in Preference Pane
None

### Detailed Explaination of Issue
Upgraded to macOS Big Sur, I got some warning on the first boot (not sure if it was because of this driver)

However now the xbox controller does not work and I cannot uninstall the extension, when I go to the system preferences pane, and click on the uninstall button, all I get is a error window, any suggestions how to manually uninstall and re-install?

**Comment by ospfranco** [comment]
I downloaded the uninstall.command from the latest release, this is the output when it runs:

```
Index Refs Address            Size       Wired      Name (Version) UUID <Linked     1  144 0                  0          0          com.apple.kpi.bsd (20.1.0) 8    2   11 0                  0          0          com.apple.kpi.dsep (20.1.0)     3  182 0                  0          0          com.apple.kpi.iokit (20.1.0)    4    0 0                  0          0          com.apple.kpi.kasan (20.1.0)    5  185 0                  0          0          com.apple.kpi.libkern (20.1.    6  163 0                  0          0          com.apple.kpi.mach (20.1.0)     7   93 0                  0          0          com.apple.kpi.private (20.1.    8  107 0                  0          0          com.apple.kpi.unsupported (2    9    2 0xffffff80031de000 0xe000     0xe000     com.apple.kec.Libm (1) FA774   10   12 0xffffff80033fc000 0x8d000    0x8d000    com.apple.kec.corecrypto (1.   11    0 0xffffff8003490000 0x8000     0x8000     com.apple.kec.pthread (1) 37   12    1 0xffffff8003552000 0x2000     0x2000     com.apple.driver.watchdog (1   13   42 0xffffff80026d2000 0x2000     0x2000     com.apple.iokit.IOACPIFamily   14   50 0xffffff8002c17000 0x28000    0x28000    com.apple.iokit.IOPCIFamily    15   14 0xffffff8001890000 0x19000    0x19000    com.apple.driver.AppleSMC (3   16    2 0xffffff800128e000 0x77000    0x77000    com.apple.driver.AppleACPIPl   17    5 0xffffff8002d2f000 0x2000     0x2000     com.apple.driver.IOSlaveProc   18    3 0xffffff8001876000 0x10000    0x10000    com.apple.driver.AppleSEPMan   19    1 0xffffff8001587000 0x4000     0x4000     com.apple.driver.AppleBusPow   20   14 0xffffff80019dc000 0x4000     0x4000     com.apple.driver.usb.AppleUS   21    3 0xffffff8003044000 0x1000     0x1000     com.apple.driver.AppleUSBHos   22   23 0xffffff8002f49000 0x8d000    0x8d000    com.apple.iokit.IOUSBHostFam   23    3 0xffffff80031c8000 0xf000     0xf000     com.apple.driver.KernelRelay   24    1 0xffffff80015fb000 0x50000    0x50000    com.apple.driver.AppleCreden   25    3 0xffffff8001668000 0x6000     0x6000     com.apple.driver.AppleEfface   26    0 0xffffff8001672000 0x6000     0x6000     com.apple.driver.AppleFDEKey   27    2 0xffffff8001b78000 0x7000     0x7000     com.apple.kext.CoreTrust (1)   28    9 0xffffff80017fc000 0x15000    0x15000    com.apple.driver.AppleMobile   29    4 0xffffff8002c52000 0x14000    0x14000    com.apple.iokit.IOSCSIArchit   30   11 0xffffff8002d37000 0x12000    0x12000    com.apple.iokit.IOStorageFam   31    1 0xffffff8002c77000 0xe000     0xe000     com.apple.iokit.IOSCSIBlockC   32    1 0xffffff80031a4000 0x1a000    0x1a000    com.apple.iokit.IOUSBMassStorageDriver (184.40.6) 1D1E24DB-C7AC-390C-9B73-C9B139D3355F <30 29 22 14 7 6 5 3    33    2 0xffffff80018e9000 0x8000     0x8000     com.apple.driver.AppleUSBTDM   34    0 0xffffff8001757000 0x80000    0x80000    com.apple.driver.AppleKeyStore (2) 2D1ED2DB-F2C2-3530-B30C-9EC4B0220160 <33 28 27 24 23 18 17 10 8 7 6 5 3 1   35    0 0xffffff80018b1000 0x7000     0x7000     com.apple.driver.AppleSSE (1   36    4 0xffffff8001aa3000 0x7000     0x7000     com.apple.iokit.CoreAnalytic   37    2 0xffffff80017f8000 0x3000     0x3000     com.apple.kext.AppleMatch (1   38    3 0xffffff8003210000 0x44000    0x44000    com.apple.security.sandbox (   39    2 0xffffff8003207000 0x8000     0x8000     com.apple.security.quarantin   40    0 0xffffff8001b80000 0x4c000    0x4c000    com.apple.iokit.EndpointSecu   41    1 0xffffff8002850000 0x6000     0x6000     com.apple.iokit.IOBluetoothP   42   11 0xffffff8002c4d000 0x3000     0x3000     com.apple.iokit.IOReportFami   43    4 0xffffff8002764000 0x9c000    0x9c000    com.apple.iokit.IOBluetoothF   44    0 0xffffff800288d000 0xc000     0xc000     com.apple.driver.DiskImages    45    0 0xffffff800295a000 0x1000     0x1000     com.apple.iokit.IOKitRegistr   46   13 0xffffff800298e000 0x17000    0x17000    com.apple.iokit.IONetworking   47    3 0xffffff8002e7e000 0x1b000    0x1b000    com.apple.iokit.IOTimeSyncFa   48    0 0xffffff8001284000 0x9000     0x9000     com.apple.nke.applicationfir   49    1 0xffffff80016ca000 0x10000    0x10000    com.apple.security.AppleImag   50    0 0xffffff8001905000 0xe000     0xe000     com.apple.AppleSystemPolicy    51    0 0xffffff800132b000 0x2000     0x2000     com.apple.driver.AppleAPIC (   52   11 0xffffff80028ca000 0x5d000    0x5d000    com.apple.iokit.IOHIDFamily    53    3 0xffffff8002cd0000 0x1000     0x1000     com.apple.iokit.IOSMBusFamil   54    0 0xffffff8001318000 0x5000     0x5000     com.apple.driver.AppleACPIEC   55    0 0xffffff800188c000 0x3000     0x3000     com.apple.driver.AppleSMBIOS   56    0 0xffffff80018ac000 0x4000     0x4000     com.apple.driver.AppleSMCRTC   57    0 0xffffff8001313000 0x2000     0x2000     com.apple.driver.AppleACPIBu   58    1 0xffffff8001652000 0x2000     0x2000     com.apple.driver.AppleEFIRun   59    2 0xffffff8001655000 0xa000     0xa000     com.apple.driver.AppleEFINVR   60    0 0xffffff80018ba000 0x10000    0x10000    com.apple.driver.AppleSmartB   61    0 0xffffff80031db000 0x1000     0x1000     com.apple.private.KextAudit    62    1 0xffffff80030e7000 0x4e000    0x4e000    com.apple.driver.usb.AppleUS   63    0 0xffffff800313e000 0x28000    0x28000    com.apple.driver.usb.AppleUS   64    0 0xffffff8002ea6000 0x63000    0x63000    com.apple.iokit.IOUSBFamily    65    0 0xffffff8003046000 0x2000     0x2000     com.apple.driver.usb.AppleUS   66    0 0xffffff800295c000 0x2a000    0x2a000    com.apple.iokit.IONVMeFamily   67    6 0xffffff8002873000 0x7000     0x7000     com.apple.iokit.IOBufferCopy   68    0 0xffffff800286d000 0x4000     0x4000     com.apple.iokit.IOBufferCopy   69    0 0xffffff8001661000 0x4000     0x4000     com.apple.driver.AppleEfface   70    3 0xffffff80019e1000 0x6000     0x6000     com.apple.driver.usb.AppleUS   71    1 0xffffff80030c2000 0x1e000    0x1e000    com.apple.driver.usb.AppleUS   72    1 0xffffff80019e8000 0xb000     0xb000     com.apple.driver.usb.AppleUS   73    0 0xffffff80030e5000 0x1000     0x1000     com.apple.driver.usb.AppleUSBVHCIBCE (1.2) B230988B-454E-3B11-BA48-9F814D4B7B8A <72 71 70 67 22 20 13 8 7 6    74    8 0xffffff8002d7f000 0xd8000    0xd8000    com.apple.iokit.IOThunderbol   75    0 0xffffff800195e000 0x30000    0x30000    com.apple.driver.AppleThunde   76    0 0xffffff8001a61000 0x3000     0x3000     com.apple.driver.AppleXsanSc   77    1 0xffffff800326c000 0x163000   0x163000   com.apple.filesystems.apfs (1677.50.1) F58A8B8C-6A8B-3186-9197-1D098B799F1A <59 49 36 30 25 10 8 7 6 5 3 2 1   78    8 0xffffff80033da000 0x17000    0x17000    com.apple.driver.corecapture   79    6 0xffffff8002945000 0x11000    0x11000    com.apple.driver.IOImageLoad   80    2 0xffffff8002c11000 0x5000     0x5000     com.apple.driver.mDNSOffload   81    5 0xffffff8002ce1000 0x3e000    0x3e000    com.apple.iokit.IOSkywalkFam   82    2 0xffffff800257a000 0x13e000   0x13e000   com.apple.iokit.IO80211FamilyV2 (1200.12.2b1) 325D373A-416D-3BE1-A9B5-79DA56C1B336 <81 78 46 28 10 8 7 6 5 3   83    6 0xffffff8002cd2000 0x6000     0x6000     com.apple.iokit.IOSerialFami   84    1 0xffffff8001391000 0x1b4000   0x1b4000   com.apple.driver.AppleBCMWLANCoreMac (1.0.0) 6EC179D1-3D5C-322F-BF7C-83228170941E <83 82 81 80 79 78 47 46 3   85    0 0xffffff8001338000 0x4f000    0x4f000    com.apple.driver.AppleBCMWLANBusInterfacePCIeMac (1) 748D388B-7129-3773-80E6-EE47DA042DA5 <84 82 81 79 78 46   86    0 0xffffff800167a000 0x2000     0x2000     com.apple.AppleFSCompression.AppleFSCompressionTypeDataless (1.0.0d1) 56142328-78AF-382A-9107-0DAE174422D8 <   87    0 0xffffff800167d000 0x9000     0x9000     com.apple.AppleFSCompression.AppleFSCompressionTypeZlib (1.0.0) 459920D3-CE05-3C80-9811-B6DEB03C1D19 <7 5 3    88    0 0xffffff8001a95000 0xc000     0xc000     com.apple.BootCache (40) CE6   89    1 0xffffff8001c37000 0x2000     0x2000     com.apple.filesystems.hfs.en   90    1 0xffffff8001bd2000 0x63000    0x63000    com.apple.filesystems.hfs.ke   91    3 0xffffff8002d5e000 0x1c000    0x1c000    com.apple.iokit.IOSurface (2   92    0 0xffffff8001562000 0x1000     0x1000     com.apple.driver.AppleBSDKex   93    0 0xffffff8003499000 0xc000     0xc000     com.apple.filesystems.tmpfs    94    0 0xffffff8001689000 0x1000     0x1000     com.apple.driver.AppleFileSy   95    1 0xffffff800171f000 0x5000     0x5000     com.apple.driver.AppleIntelL   96    1 0xffffff800172e000 0x7000     0x7000     com.apple.driver.AppleIntelL   97    1 0xffffff8001736000 0xd000     0xd000     com.apple.driver.AppleIntelLpssI2CController (3.0.60) 5CAEA50F-2DB1-3DB4-8146-7DE513B743A3 <96 95 13 8 6 5 3   98    0 0xffffff80016a0000 0x6000     0x6000     com.apple.driver.AppleHPM (3   99    3 0xffffff8001916000 0x17000    0x17000    com.apple.driver.AppleThunde  100    0 0xffffff800192f000 0xa000     0xa000     com.apple.driver.AppleThunde  101    0 0xffffff8001997000 0x4000     0x4000     com.apple.driver.AppleThunde  102    0 0xffffff8001a78000 0x2000     0x2000     com.apple.driver.BCMWLANFirm  103    0 0xffffff8001a7b000 0x7000     0x7000     com.apple.driver.BCMWLANFirm  104    0 0xffffff8001a87000 0x4000     0x4000     com.apple.driver.BCMWLANFirm  105    0 0xffffff8001a8e000 0x4000     0x4000     com.apple.driver.BCMWLANFirm  106    2 0xffffff800303f000 0x3000     0x3000     com.apple.driver.usb.AppleUSBHostCompositeDevice (1.2) 49116B0D-FBFC-3440-8C37-1F7BEEEEFDA4 <22 20 7 6 5 3 1  107    3 0xffffff8001a24000 0x2000     0x2000     com.apple.driver.usb.network  108    2 0xffffff80019d8000 0x2000     0x2000     com.apple.driver.usb.cdc (5.  109    0 0xffffff8001a1b000 0x7000     0x7000     com.apple.driver.usb.cdc.ncm  110    0 0xffffff80019f7000 0x3000     0x3000     com.apple.driver.usb.cdc.ecm  111    0 0xffffff8003198000 0xa000     0xa000     com.apple.driver.usb.IOUSBHo  112    0 0xffffff8003049000 0x2b000    0x2b000    com.apple.driver.usb.AppleUS  113    0 0xffffff800303c000 0x2000     0x2000     com.apple.driver.usb.AppleUS  114    1 0xffffff8002d34000 0x2000     0x2000     com.apple.iokit.IOSlowAdapti  115    0 0xffffff7f9f880000 0x1000     0x1000     com.apple.driver.AppleIntelS  116   22 0xffffff7f9fcb3000 0x2f000    0x2f000    com.apple.iokit.IOGraphicsFa  117    9 0xffffff7f9e40e000 0x4000     0x4000     com.apple.AppleGraphicsDevic  118    0 0xffffff7f9e404000 0x7000     0x7000     com.apple.AppleGPUWrangler (  119    3 0xffffff7f9fb5b000 0x6a000    0x6a000    com.apple.iokit.IOAcceleratorFamily2 (439.35.4) BA67BC61-7BC3-3A5B-8D09-EA01DE06400C <116 91 42 28 14 8 7 6   120    0 0xffffff7f9e8aa000 0xbe000    0xbe000    com.apple.driver.AppleIntelCFLGraphicsFramebuffer (16.0.0) 454E9AD8-8527-30C3-BB46-FBBA098EA330 <119 117 116  121    1 0xffffff80034a6000 0xab000    0xab000    com.apple.vecLib.kext (1.2.0  122    3 0xffffff8002735000 0x1e000    0x1e000    com.apple.iokit.IOAudioFamil  123    4 0xffffff7f9fcf8000 0x9000     0x9000     com.apple.iokit.IONDRVSuppor  124    0 0xffffff7f9e384000 0x5e000    0x5e000    com.apple.driver.AppleGFXHDA  125    1 0xffffff7f9e65c000 0x4000     0x4000     com.apple.iokit.IOHDAFamily   126    0 0xffffff7f9e53c000 0x13000    0x13000    com.apple.driver.AppleHDAController (283.15) 6CF7DB7D-FADC-3C55-B7DB-0B82CCCF2AF3 <125 122 116 14 8 7 6 5 3   128    0 0xffffff7f9f8df000 0x1000     0x1000     com.apple.driver.AppleSMBusP  129    0 0xffffff7f9e312000 0x2000     0x2000     com.apple.driver.AppleFIVRDr  130    0 0xffffff7f9e2f9000 0xc000     0xc000     com.apple.driver.AppleDiskIm  131    0 0xffffff7f9e664000 0xa000     0xa000     com.apple.driver.AppleHV (1)  132    0 0xffffff7f9f9f3000 0x3000     0x3000     com.apple.Dont_Steal_Mac_OS_  133    2 0xffffff8002bfd000 0x2000     0x2000     com.apple.iokit.IOEthernetAV  134    1 0xffffff7f9fd5e000 0x68000    0x68000    com.apple.plugin.IOgPTPPlugi  135    0 0xffffff7f9faf6000 0x13000    0x13000    com.apple.iokit.IOAVBFamily   136    0 0xffffff7f9fbe4000 0x7000     0x7000     com.apple.iokit.IOBluetoothS  137    0 0xffffff7f9fdef000 0x18000    0x18000    com.apple.driver.usb.AppleUS  138    0 0xffffff7f9fe0d000 0x3000     0x3000     com.apple.iokit.IOUserEthern  139    0 0xffffff7f9fe27000 0x3000     0x3000     com.apple.driver.LuaHardware  140    0 0xffffff7fa069a000 0x8000     0x8000     com.apple.driver.pmtelemetry  141    1 0xffffff800193b000 0x20000    0x20000    com.apple.driver.AppleThunderboltDPOutAdapter (8.1.4) FB819686-87AA-3B32-8A27-9EB17456C452 <99 74 13 6 5 3 1  142    0 0xffffff7f9f90a000 0x8000     0x8000     com.apple.driver.AppleThunde  143    0 0xffffff7f9f91b000 0x3d000    0x3d000    com.apple.driver.AppleThunde  144    0 0xffffff7f9e401000 0x2000     0x2000     com.apple.AGDCPluginDisplayM  145    1 0xffffff7f9f8d4000 0x7000     0x7000     com.apple.driver.AppleSMBusC  146    0 0xffffff7f9f885000 0xb000     0xb000     com.apple.driver.AppleMCCSCo  147    6 0xffffff7f9fd03000 0x4000     0x4000     com.apple.driver.IOPlatformP  148    0 0xffffff7f9f552000 0x3000     0x3000     com.apple.driver.AppleIntelP  149    1 0xffffff7f9fd2a000 0x14000    0x14000    com.apple.driver.X86Platform  150    1 0xffffff7f9fd1c000 0x9000     0x9000     com.apple.driver.IOPlatformP  151    0 0xffffff7f9fd09000 0xd000     0xd000     com.apple.driver.ACPI_SMC_PlatformPlugin (1.0.0) A578488A-73BF-3FA0-83A9-371082819A25 <150 147 15 14 13 8 7   152    2 0xffffff7f9e3fa000 0x1000     0x1000     com.apple.driver.AppleGraphi  153    0 0xffffff7f9e44a000 0x13000    0x13000    com.apple.driver.AppleMuxControl2 (6.1.27) 8CD57AFF-DF15-321D-9E0A-0EF2211FB35E <152 117 116 14 13 8 7 6 5 3  154    2 0xffffff7f9e23f000 0x2000     0x2000     com.apple.driver.AppleBackli  155    0 0xffffff7f9e23a000 0x3000     0x3000     com.apple.driver.AppleBackli  156    0 0xffffff7f9e3fc000 0x3000     0x3000     com.apple.driver.AGDCBacklightControl (6.1.27) 0EFC271B-2C17-3336-9E9A-0B408965125E <154 117 116 13 8 6 5 3   157    0 0xffffff7f9f9e7000 0x9000     0x9000     com.apple.driver.AppleBridge  158    0 0xffffff7f9e229000 0x3000     0x3000     com.apple.driver.AppleAVEBri  159    0 0xffffff7f9f9da000 0xa000     0xa000     com.apple.driver.BridgeAudio  160    2 0xffffff7f9e131000 0xc7000    0xc7000    com.apple.kext.AMDSupport (4  161    0 0xffffff7f80f6e000 0x65000    0x65000    com.apple.kext.AMD9500Contro  162    0 0xffffff7f9e416000 0x9000     0x9000     com.apple.driver.AppleGraphicsDevicePolicy (6.1.27) 60206AFF-F0D8-366C-944B-97E6BA5CE7B8 <152 117 116 14 13   163    2 0xffffff7f9f897000 0x10000    0x10000    com.apple.driver.AppleOnboar  164    1 0xffffff7f9f53a000 0x1000     0x1000     com.apple.driver.AppleIntelLpssUARTCommon (3.0.60) A2391317-4AC3-3C90-8CEE-BCF94B2D7B4C <163 83 14 13 8 6 5   165    0 0xffffff7f9f53e000 0x1000     0x1000     com.apple.driver.AppleIntelLpssUARTv1 (3.0.60) 2E639E17-CCCD-3C14-9DDF-C2912A395114 <164 163 83 14 13 8 6 5   166    0 0xffffff7f9f212000 0xb7000    0xb7000    com.apple.driver.AppleIntelKBLGraphics (16.0.0) FEF07355-0C62-3DE2-841F-3A307987D15C <119 116 91 14 8 7 6 5   167    0 0xffffff7f81013000 0x3000     0x3000     com.apple.kext.AMDRadeonServ  168    1 0xffffff800282b000 0x5000     0x5000     com.apple.iokit.IOBluetoothHostControllerTransport (8.0.1f5) 210F2309-246F-3FBB-B8BC-4FB23C112EE8 <43 22 14   169    0 0xffffff8002831000 0x4000     0x4000     com.apple.iokit.IOBluetoothHostControllerUARTTransport (8.0.1f5) CA650C0E-949E-3D10-8A26-04CFF15C1620 <168 8  170    0 0xffffff7f814a6000 0x3000     0x3000     com.apple.kext.AMDRadeonX400  171    0 0xffffff7f81018000 0x43b000   0x43b000   com.apple.kext.AMDRadeonX400  172    0 0xffffff7f9f9ca000 0x3000     0x3000     com.apple.driver.AppleUpstre  173    0 0xffffff7f83b10000 0x149000   0x149000   com.apple.kext.AMDRadeonX410  174    0 0xffffff7f9e367000 0x17000    0x17000    com.apple.fileutil (20.036.1  175    0 0xffffff7f80fe8000 0x27000    0x27000    com.apple.kext.AMDFramebuffe  176    1 0xffffff7fa0723000 0x3000     0x3000     com.apple.kext.triggers (1.0  177    0 0xffffff7fa05fa000 0x8000     0x8000     com.apple.filesystems.autofs  178    0 0xffffff800168b000 0x1000     0x1000     com.apple.driver.AppleHIDALS  179    2 0xffffff80016df000 0xd000     0xd000     com.apple.driver.AppleInputD  180    2 0xffffff8001820000 0x14000    0x14000    com.apple.driver.AppleMultit  181    0 0xffffff800132e000 0x7000     0x7000     com.apple.driver.AppleActuatorDriver (4400.28) EC758804-8E2F-3A39-B731-413E00721EFD <180 179 52 42 8 6 5 3 1  182    0 0xffffff800168d000 0x4000     0x4000     com.apple.driver.AppleHIDKey  183    1 0xffffff800285b000 0xf000     0xf000     com.apple.driver.IOBluetooth  184    1 0xffffff80019c2000 0x6000     0x6000     com.apple.driver.AppleHSBlue  185    0 0xffffff80019cb000 0x7000     0x7000     com.apple.driver.AppleTopCaseHIDEventDriver (4000.27) 8C6C3148-9487-3A6A-9050-1907AF66399C <184 180 52 7 6 5  186    1 0xffffff7f9fd3f000 0x6000     0x6000     com.apple.driver.X86Platform  187    0 0xffffff7f9e466000 0x1d000    0x1d000    com.apple.driver.AGPM (119)   188    0 0xffffff7f9f8d0000 0x2000     0x2000     com.apple.driver.ApplePlatfo  189    0 0xffffff7f9f9d5000 0x3000     0x3000     com.apple.driver.AudioAUUC (  190    2 0xffffff8002cbe000 0xb000     0xb000     com.apple.iokit.IOSCSIParall  191    0 0xffffff7fa1650000 0xb000     0xb000     com.highpoint-tech.kext.High  192    0 0xffffff7fa16f1000 0x2f000    0x2f000    com.softraid.driver.SoftRAID  193    0 0xffffff7fa165f000 0x85000    0x85000    com.highpoint-tech.kext.HighUninstalled 360Controller successfully.5-9996CA7A54B9 <190 14 6 5 3>
```

However I still cannot uninstall the extension from the system preferences and I cannot install the latest version

**Comment by Sn00perton** [comment]
Also having problem of Xbox One controller not recognized after Big Sur update. Is there an alternative?

**Comment by watchoutalien** [comment]
same issue here

**Comment by Clashbuster** [comment]
same here, updated to big sur today no longer working.

**Comment by c0d3x** [comment]
Yup same issue her when using the installer.
![image](https://user-images.githubusercontent.com/661911/99129451-ebf40400-260d-11eb-9cd8-1583a3d4ac48.png)

**Comment by Sn00perton** [comment]
So I fixed this issue for myself but it is not what you want to hear haha.

To uninstall the 360 Controller Pref Pane I used CleanMyMacX (program I already had) and under the Extensions tab the old 360 Controller can be removed 

To get my Xbox One controller to work with my game again I downloaded and installed Parallels and Windows, bought on discount through my post secondary software store. Paired Xbox One controller to Windows, run Steam and game through Windows, and now everything works fine for my game.

**Comment by KingWASD** [comment]
This is due to 360Controller being a "legacy" system extension. The 360Controller preferences pane eventually just disappeared for me some time after failing to uninstall.

**Comment by rdonadono** [comment]
same issue

**Comment by raffaeleg4** [comment]
Same. I was aware, though. There was a warning starting with macOS Catalina, that legacy extension wouldn't work anymore with the next version of macOS. I still have the Preference Pane, but with no reaction. Drew Mills developer is already allowed, but nothing works. 
![Schermata 2020-11-14 alle 17 02 52](https://user-images.githubusercontent.com/56472056/99151402-3d96a000-269b-11eb-951d-0ade101987dd.jpg)

**Comment by thimoti26** [comment]
hi, I have the same problem after upgrading to Big Sur :'(.
I have the problem above (allow driver, without seeing it in security) . 
I tried to reinstall the app (apha.6), nothing more. 
I have this on startup if it could help : 
<img width="305" alt="Capture d’écran 2020-11-14 à 22 43 12" src="https://user-images.githubusercontent.com/16595306/99157797-83b82780-26cc-11eb-97cc-17f7b649013a.png">

**Comment by davidprati** [comment]
Same issue

**Comment by amoneptah** [comment]
Well, I guess we all in here for the same reason... If anyone find a way (which not include downloading a Windows partition on my Mac, haha...) let us know <3 !

**Comment by ospfranco** [comment]
Please, stop commenting without any additional information, it only spams the maintainers/owners of the repo, you can like the original issue and that should be enough

**Comment by jpv123** [comment]
It looks like this is a problem related with the kext of the package since the Big Sur update. A few console logs show the following information which could be useful:

`library rebuild request failed: Extension with identifiers com.mice.driver.Xbox360Controller,com.mice.driver.WirelessOneController,com.mice.driver.Wireless360Controller,com.mice.driver.WirelessGamingReceiver not approved to load. Please approve using System Preferences.`

`Kernel Extension BLOCKED: Kext (G947KKM5RL, com.mice.driver.Xbox360Controller) version: b6d2d39ae77703c5c2c3f995d68a539252e515b2`

@FranticRain @ospfranco Can you please take a look?

**Comment by FranticRain** [comment]
360Controller doesn't work in Big Sur and never will. This project is dead. Use a Bluetooth Xbox One controller if you can, since they are now officially supported. Same with the Dualshock 4.

**Comment by ospfranco** [comment]
Alright, you heard the man, nothing to see here, closing this issue

**Comment by silentj** [comment]
I modified the steps from [this discussion](https://developer.apple.com/forums/thread/651132?answerId=650654022#650654022) to get the driver working for my wired Microsoft Xbox 360 controller on Big Sur 11.1. 

No guarantee this will work for the other controller types and it's likely the driver will break with a future release of macOS. But if you don't have any other controller options, this might help.

* Reboot to recovery mode (CMD+R at boot) and open up the terminal
* Disable System Integrity Protection: `csrutil disable`
* Reboot
* Install the [1.0.0-alpha.6 release](https://github.com/360Controller/360Controller/releases/tag/v1.0.0-alpha.6)
  * I still saw "The installation failed" when installing.
* Allow the driver in System Preferences -> Security & Privacy
  * If you don't see the prompt to allow a driver by "Drew Mills", then something has gone wrong and the above steps haven't worked.
* Reboot to recovery mode again and open up the terminal
* Add an exemption for the 360 drivers: `spctl kext-consent add G947KKM5RL` 
  * I got the ID of the driver using [this method](https://technology.siprep.org/getting-the-team-id-of-kernel-extensions-in-macos-10-13-and-higher/)
* Re-enable System Integrity Protection: `csrutil enable`
* Reboot

**Comment by njrmay** [comment]
> I modified the steps from [this discussion](https://developer.apple.com/forums/thread/651132?answerId=650654022#650654022) to get the driver working for my wired Microsoft Xbox 360 controller on Big Sur 11.1.
> 
> No guarantee this will work for the other controller types and it's likely the driver will break with a future release of macOS. But if you don't have any other controller options, this might help.
> 
>     * Reboot to recovery mode (CMD+R at boot) and open up the terminal
> 
>     * Disable System Integrity Protection: `csrutil disable`
> 
>     * Reboot
> 
>     * Install the [1.0.0-alpha.6 release](https://github.com/360Controller/360Controller/releases/tag/v1.0.0-alpha.6)
>       
>       * I still saw "The installation failed" when installing.
> 
>     * Allow the driver in System Preferences -> Security & Privacy
>       
>       * If you don't see the prompt to allow a driver by "Drew Mills", then something has gone wrong and the above steps haven't worked.
> 
>     * Reboot to recovery mode again and open up the terminal
> 
>     * Add an exemption for the 360 drivers: `spctl kext-consent add G947KKM5RL`
>       
>       * I got the ID of the driver using [this method](https://technology.siprep.org/getting-the-team-id-of-kernel-extensions-in-macos-10-13-and-higher/)
> 
>     * Re-enable System Integrity Protection: `csrutil enable`
> 
>     * Reboot

omg thank you this worked for me

**Comment by NagoLazaro** [comment]
> I modified the steps from [this discussion](https://developer.apple.com/forums/thread/651132?answerId=650654022#650654022) to get the driver working for my wired Microsoft Xbox 360 controller on Big Sur 11.1.
> 
> No guarantee this will work for the other controller types and it's likely the driver will break with a future release of macOS. But if you don't have any other controller options, this might help.
> 
> * Reboot to recovery mode (CMD+R at boot) and open up the terminal
> * Disable System Integrity Protection: `csrutil disable`
> * Reboot
> * Install the [1.0.0-alpha.6 release](https://github.com/360Controller/360Controller/releases/tag/v1.0.0-alpha.6)
>   
>   * I still saw "The installation failed" when installing.
> * Allow the driver in System Preferences -> Security & Privacy
>   
>   * If you don't see the prompt to allow a driver by "Drew Mills", then something has gone wrong and the above steps haven't worked.
> * Reboot to recovery mode again and open up the terminal
> * Add an exemption for the 360 drivers: `spctl kext-consent add G947KKM5RL`
>   
>   * I got the ID of the driver using [this method](https://technology.siprep.org/getting-the-team-id-of-kernel-extensions-in-macos-10-13-and-higher/)
> * Re-enable System Integrity Protection: `csrutil enable`
> * Reboot

@FranticRain @ospfranco The solution shared by @silentj  worked for me right away. I'm Big Sur 11.1.1 and my Xbox 360 wireless controller works perfectly.

**Comment by michael80-8008** [comment]
> I modified the steps from [this discussion](https://developer.apple.com/forums/thread/651132?answerId=650654022#650654022) to get the driver working for my wired Microsoft Xbox 360 controller on Big Sur 11.1.
> 
> No guarantee this will work for the other controller types and it's likely the driver will break with a future release of macOS. But if you don't have any other controller options, this might help.
> 
> * Reboot to recovery mode (CMD+R at boot) and open up the terminal
> * Disable System Integrity Protection: `csrutil disable`
> * Reboot
> * Install the [1.0.0-alpha.6 release](https://github.com/360Controller/360Controller/releases/tag/v1.0.0-alpha.6)
>   
>   * I still saw "The installation failed" when installing.
> * Allow the driver in System Preferences -> Security & Privacy
>   
>   * If you don't see the prompt to allow a driver by "Drew Mills", then something has gone wrong and the above steps haven't worked.
> * Reboot to recovery mode again and open up the terminal
> * Add an exemption for the 360 drivers: `spctl kext-consent add G947KKM5RL`
>   
>   * I got the ID of the driver using [this method](https://technology.siprep.org/getting-the-team-id-of-kernel-extensions-in-macos-10-13-and-higher/)
> * Re-enable System Integrity Protection: `csrutil enable`
> * Reboot

Works for me too
